### ISSUE TITLE
commitBuffer: invalid argument (invalid character)

### ISSUE THREAD

**Issue by mitchellwrosen** [blitzcode/hackage-diff#4]
```
$ hackage-diff transformers 0.4.3.0 0.5.0.0
Downloading / Reading Hoogle DBs...
Parsing Hoogle DBs...
Comparing Hoogle DBs...

--- Diff for | 0.4.3.0 hackage-diff: <stdout>: commitBuffer: invalid argument (invalid character)
```

**Comment by blitzcode** [comment]
Interesting, don't really know what that error is about, and it seems to work here. What OS is this happening on?

**Comment by mitchellwrosen** [comment]
Hm. This is on Arch Linux.

**Comment by blitzcode** [comment]
So it looks like it crashes as soon as it prints the 1st non-ASCII character, I also found this:

http://stackoverflow.com/questions/27616611/run-time-exception-when-attempting-to-print-a-unicode-character

Really strange, I use Unicode & UTF-8 characters all the time to spice up terminal output, never had an issue before.

What happens if you do something like `putStrLn "→"` in a small program or ghci?

**Comment by mitchellwrosen** [comment]
Huh, it was a locale setting issue, I think perhaps due to fish shell ignoring `VAR=val` syntax and instead preferring `set -x VAR val`. So, my `/etc/locale.conf` was not being properly read.

Anyways, thanks for debugging this for me! =)

**Comment by blitzcode** [comment]
No problem, didn't even know this was a thing to worry about ;-)
